DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS registeredrole;
DROP TABLE IF EXISTS user;

CREATE TABLE role (
 id INT AUTO_INCREMENT  PRIMARY KEY,
 rolename  VARCHAR(250) NOT NULL
);
CREATE TABLE user (
 id INT AUTO_INCREMENT  PRIMARY KEY,
  firstName  VARCHAR NOT NULL,
  lastName  VARCHAR NOT NULL
);
CREATE TABLE registeredRole (
 id INT AUTO_INCREMENT  PRIMARY KEY,
  userId  INT  NOT NULL REFERENCES User(id),
  roleId  INT  NOT NULL REFERENCES Role(id)
);




INSERT INTO role (rolename) VALUES('ADMINISTRATOR'),('DEVELOPER');